/**
 * Codegen — emits JavaScript from a parsed .nv FileNode.
 *
 * Two targets:
 *  - "runtime" : uses @neurova/runtime (h, signal, effect)
 *  - "react"   : uses React + a small adapter that bridges signals to
 *                React state via useSyncExternalStore.
 *
 * State desugaring:
 *   `state count = 0`
 *     → const __nv_count = signal(0)
 *       const count = Object.assign(__nv_count[0], { set: __nv_count[1] })
 *
 * In templates, `count()` reads the current value reactively, and
 * `count.set(next)` writes.
 */

import type {
  AttrNode,
  ComponentNode,
  ElementNode,
  FileNode,
  StatementNode,
  TemplateChild,
} from './ast.js'

export type EmitTarget = 'runtime' | 'react'

export interface EmitOptions {
  target?: EmitTarget
  /** Module specifier override for the runtime import. */
  runtimeModule?: string
  /** Whether to emit `// @ts-nocheck` at the top of the file. */
  tsNoCheck?: boolean
}

export function emit(file: FileNode, opts: EmitOptions = {}): string {
  const target = opts.target ?? 'runtime'
  const runtimeModule = opts.runtimeModule ?? '@neurova/runtime'

  const out: string[] = []
  if (opts.tsNoCheck) out.push('// @ts-nocheck')
  out.push('// generated by @neurova/compiler — do not edit')

  if (target === 'runtime') {
    out.push(`import { h, signal, effect, computed, For } from '${runtimeModule}'`)
  } else {
    out.push(`import * as React from 'react'`)
    out.push(`import { signal, effect } from '${runtimeModule}'`)
    out.push(`import { useSyncExternalStore as __nv_useSync } from 'react'`)
  }

  for (const imp of file.imports) {
    out.push(`import ${imp.source}`)
  }

  for (const comp of file.components) {
    out.push(emitComponent(comp, target))
  }

  if (file.components.length > 0) {
    out.push(`export default ${file.components[0]?.name}`)
  }

  return out.join('\n')
}

function emitComponent(comp: ComponentNode, target: EmitTarget): string {
  const lines: string[] = []
  if (target === 'runtime') {
    lines.push(`export function ${comp.name}(${comp.params || 'props'}) {`)
  } else {
    lines.push(`export function ${comp.name}(${comp.params || 'props'}) {`)
    // For React target, opens with a useReducer hack to force re-render
    // whenever any signal read during render changes.
    lines.push('  const [, __nv_force] = React.useReducer((x) => x + 1, 0)')
    lines.push('  React.useEffect(() => {')
    lines.push('    const dispose = effect(() => { __nv_render(); __nv_force() })')
    lines.push('    return dispose')
    lines.push('  }, [])')
    lines.push('  function __nv_render() {}')
  }

  for (const stmt of comp.statements) {
    lines.push(`  ${emitStatement(stmt)}`)
  }

  if (target === 'runtime') {
    lines.push(`  return ${emitTemplate(comp.template, target)}`)
  } else {
    lines.push(`  return ${emitTemplate(comp.template, target)}`)
  }

  lines.push('}')
  return lines.join('\n')
}

function emitStatement(stmt: StatementNode): string {
  switch (stmt.kind) {
    case 'State': {
      const tmp = `__nv_${stmt.name}`
      return `const ${tmp} = signal(${stmt.init}); const ${stmt.name} = Object.assign(${tmp}[0], { set: ${tmp}[1] });`
    }
    case 'Binding':
      return `${stmt.keyword} ${stmt.name} = ${stmt.init};`
    case 'Effect':
      return `effect(() => {${stmt.body}});`
    case 'ExprStmt':
      return `${stmt.expr};`
  }
}

function emitTemplate(node: ElementNode, target: EmitTarget): string {
  const isComponent = /^[A-Z]/.test(node.tag)
  const tagExpr = isComponent ? node.tag : JSON.stringify(node.tag)
  const propsObj = emitProps(node.attrs)
  const childParts = node.children.map((c) => emitChild(c, target))

  if (target === 'runtime') {
    if (childParts.length === 0) return `h(${tagExpr}, ${propsObj})`
    return `h(${tagExpr}, ${propsObj}, ${childParts.join(', ')})`
  }
  // react target
  if (childParts.length === 0) {
    return `React.createElement(${tagExpr}, ${propsObj})`
  }
  return `React.createElement(${tagExpr}, ${propsObj}, ${childParts.join(', ')})`
}

function emitProps(attrs: AttrNode[]): string {
  if (attrs.length === 0) return 'null'
  const parts: string[] = []
  for (const a of attrs) {
    if (a.kind === 'StaticAttr') {
      parts.push(`${JSON.stringify(a.name)}: ${JSON.stringify(a.value)}`)
    } else if (a.kind === 'ExprAttr') {
      // Always pass as a function so the runtime can re-evaluate; for
      // React target this is a plain prop value.
      parts.push(`${JSON.stringify(a.name)}: (${a.expr})`)
    } else {
      // EventAttr — emit on:event for runtime, onEvent for React.
      parts.push(`${JSON.stringify(`on:${a.event}`)}: (${a.expr})`)
    }
  }
  return `{ ${parts.join(', ')} }`
}

function emitChild(child: TemplateChild, target: EmitTarget): string {
  if (child.kind === 'Text') return JSON.stringify(child.value)
  if (child.kind === 'Mustache') {
    if (target === 'runtime') {
      // Wrap in a thunk so reactive reads inside re-run on change.
      return `() => (${child.expr})`
    }
    return `(${child.expr})`
  }
  return emitTemplate(child, target)
}
